---
title: "Plotly Examples"
author: "Guangling Xu"
date: "2019/10/22"
output: 
html_document:
    toc: true
    toc_float: true
---

 My name is Guangling and I make websites _with interactive graphics_ !!!
 
```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)

library(plotly)
```


## let us make some plots

```{r}
data("nyc_airbnb")
```

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% 
  sample_n(5000) ## give 5000 samples from the dataset
```


## Plot scatterplot

```{r}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
## mode = "markers" just put the points but not line the points up.
```

```{r}
common_neighborhoods =
  nyc_airbnb %>% 
  count(neighbourhood, sort = TRUE) %>% 
  top_n(8) %>% 
  select(neighbourhood)

inner_join(nyc_airbnb, common_neighborhoods, by = "neighbourhood") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% ## increasing order with prices
  plot_ly(y = ~price, color = ~neighbourhood, type = "box",
          colors = "Set2")
```

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, n)
  ) %>% 
  plot_ly(x = ~neighbourhood, y = ~n , type = "bar")
```


